version: "3.3"
services:
  caddy:
    image: caddy:2.3.0
    restart: always
    networks:
      - internet-access
      - sequentialread
      - gitea
      - ghost
    ports:
      - "80:80"
      - "443:443"
    command: ["caddy", "run", "-config", "/config/config.json"]
    volumes:
      - type: bind
        source: ./caddy/config
        target: /config
        read_only: true
      - type: bind
        source: ./caddy/data
        target: /data
      - type: volume
        source: caddy-socket-volume
        target: /caddysocket

  caddy-config:
    image: sequentialread/caddy-config:0.0.6
    restart: always
    userns_mode: "host"
    networks:
      - sequentialread
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: caddy-socket-volume
        target: /caddysocket

  stream:
    image: sequentialread/owncast-caching-proxy:0.0.15  
    restart: always
    networks:
      - internet-access # stream has to have the ability to dial out (talk to the laptop)
    command: 192.168.0.46:8080
    volumes:
      - type: bind
        source: ./owncast-caching-proxy/cache
        target: /app/cache
    environment:
      DEBUG: 0
    labels:
      sequentialread-8080-public-port: 443
      sequentialread-8080-public-protocol: https
      sequentialread-8080-public-hostnames: "stream.beta.sequentialread.com"
      sequentialread-8080-container-protocol: http

  pwm:
    image: sequentialread/sequentialread-password-manager:1.2.0
    restart: always
    networks:
      - sequentialread
    environment:
      - SEQUENTIAL_READ_PWM_S3_BUCKET_NAME=sequentialread-pwm
      - SEQUENTIAL_READ_PWM_S3_BUCKET_REGION=us-west-2
      - SEQUENTIAL_READ_PWM_AWS_ACCESS_KEY_ID=AKIAJHP3D55MARVAFOMQ
      - SEQUENTIAL_READ_PWM_AWS_SECRET_ACCESS_KEY=${PWM_S3_SECRET_ACCESS_KEY}
    volumes:
      - type: bind
        source: ./pwm/data
        target: /data
    labels:
      sequentialread-8073-public-port: 443
      sequentialread-8073-public-protocol: https
      sequentialread-8073-public-hostnames: "pwm.beta.sequentialread.com"
      sequentialread-8073-container-protocol: http

  picopublish:
    image: sequentialread/picopublish:0.1.3
    restart: always
    networks:
      - sequentialread
    environment:
      - PICO_PUBLISH_PASSWORD=${PICOPUBLISH_PASSWORD}
    volumes:
      - type: bind
        source: ./picopublish/data
        target: /picopublish/data
    labels:
      sequentialread-8080-public-port: 443
      sequentialread-8080-public-protocol: https
      sequentialread-8080-public-hostnames: "picopublish.beta.sequentialread.com"
      sequentialread-8080-container-protocol: http

  webclip:
    image: sequentialread/webclip:0.0.0
    restart: always
    networks:
      - sequentialread
    labels:
      sequentialread-8080-public-port: 443
      sequentialread-8080-public-protocol: https
      sequentialread-8080-public-hostnames: "webclip.beta.sequentialread.com"
      sequentialread-8080-container-protocol: http

  ghost:
    image: ghost:3.41-alpine
    restart: always
    networks:
      - ghost
    volumes:
      - type: bind
        source: ./ghost
        target: /var/lib/ghost/content
    environment:
      - NODE_ENV=production
      - url=https://beta.sequentialread.com
      - database__client=sqlite3 
      - database__connection__filename=content/data/ghost-prod.db 
      - database__useNullAsDefault=true
      - database__debug=false
      - mail__from=gitlab.sequentialread.com@gmail.com
      - mail__transport=SMTP
      - mail__options__host=smtp.gmail.com
      - mail__options__port=465
      - mail__options__auth__user=gitlab.sequentialread.com@gmail.com
      - mail__options__auth__pass=${GMAIL_PASSWORD}
    labels:
      sequentialread-2368-public-port: 443
      sequentialread-2368-public-protocol: https
      sequentialread-2368-public-hostnames: "beta.sequentialread.com,www.beta.sequentialread.com"
      sequentialread-2368-container-protocol: http


  comments:
    image: sequentialread/comments:0.1.4
    restart: always
    networks:
      - ghost
    volumes:
      - type: bind
        source: ./comments
        target: /app/data
    environment:
      - COMMENTS_LISTEN_PORT=2369
      - COMMENTS_CORS_ORIGINS=https://sequentialread.com,https://www.sequentialread.com,https://beta.sequentialread.com,https://www.beta.sequentialread.com
      - COMMENTS_RECAPTCHA_SITE_KEY=6Le7MB4TAAAAAIIky6MbeT---DSCSXic3pQSTPLh
      - COMMENTS_RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - COMMENTS_EMAIL_HOST=smtp.gmail.com
      - COMMENTS_EMAIL_PORT=465
      - COMMENTS_EMAIL_USER=gitlab.sequentialread.com@gmail.com
      - COMMENTS_EMAIL_PASSWORD=${GMAIL_PASSWORD}
      - COMMENTS_NOTIFICATION_TARGET=forest.n.johnson@gmail.com
      - COMMENTS_ADMIN_PASSWORD=${COMMENTS_ADMIN_PASSWORD}
    labels:
      sequentialread-2369-public-port: 443
      sequentialread-2369-public-protocol: https
      sequentialread-2369-public-hostnames: "comments.beta.sequentialread.com"
      sequentialread-2369-container-protocol: http

  gitea:
    image: gitea/gitea:1.12.4
    restart: always
    ports:
      - "10022:10022"
    networks:
      - gitea
    volumes:
      - type: bind
        source: ./gitea/data
        target: /data
    environment:
      - APP_NAME='SequentialRead Git'
      - SSH_PORT=10022
      - SSH_LISTEN_PORT=10022
      - ROOT_URL=https://git.beta.sequentialread.com
      - DISABLE_REGISTRATION=true
      - INSTALL_LOCK=true
      - SECRET_KEY=${GITEA_SECRET_KEY}
      - DB_TYPE=mysql
      - DB_HOST=gitea-mariadb
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${GITEA_MARIADB_GITEA_PASSWORD}
    depends_on:
      - gitea-mariadb
    labels:
      sequentialread-3000-public-port: 443
      sequentialread-3000-public-protocol: https
      sequentialread-3000-public-hostnames: "git.beta.sequentialread.com"
      sequentialread-3000-container-protocol: http
  gitea-mariadb:
    image: mariadb:10
    restart: always
    networks:
      - gitea
    volumes:
      - type: bind
        source: ./gitea-mariadb/
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${GITEA_MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${GITEA_MARIADB_GITEA_PASSWORD}

networks:
  internet-access:
    driver: bridge
  gitea:
    driver: bridge
    internal: true
  sequentialread:
    driver: bridge
    internal: true
  ghost:
    driver: bridge
    internal: true

volumes:
  caddy-socket-volume:

