FROM caddy:2.3.0

# curl https://greenhouse-alpha.server.garden/releases/caddy-v2.4.0-beta.2-forest-078f12e0-b4a8-linux-arm.gz | gunzip > caddy
COPY caddy /usr/bin/caddy

# docker build -t sequentialread/caddy:v2.4.0-beta.2-forest-078f12e0-b4a8 .
