{
 "title": "sequentialread.com",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "SHOW TAG VALUES ON \"sequentialread\" WITH KEY = \"com.docker.compose.service\""
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM Usage by Service",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100-max(\"usage_idle\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT 100-mean(\"available_percent\") FROM \"mem\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host IOPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"reads\"), 1s)+non_negative_derivative(mean(\"writes\"), 1s)  FROM \"diskio\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null) ",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Sent/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host bytes recv/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 1s)-non_negative_derivative(mean(\"bytes_recv\"), 1s)  FROM \"net\" WHERE $timeFilter GROUP BY time($__interval), \"host\", \"interface\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Recv/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host bytes recv/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "docker daemon file descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host docker file descriptors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_used_file_descriptors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Docker metrics alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "this only exists so i can get a \"no  data\" alert when telegraf stops getting docker statss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "service" },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "$service CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $service CPU usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service RAM usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] RAM usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service block IO bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] block storage IO bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "com.docker.compose.service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT non_negative_derivative(mean(\"io_serviced_recursive_total\"), 1s)+non_negative_derivative(mean(\"io_service_recursive_total\"), 1s)  FROM \"docker_container_blkio\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "$service network io bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.compose.service]] network bandwidth bytes/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"), 1s) + non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"docker_container_net\" WHERE (\"com.docker.compose.service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"com.docker.compose.service\" fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}